import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "./CustomCursor";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable}`}>
        <CustomCursor />

        <div className="navbar">
          <div className="nav-left">
            <img src="/rox1.png" className="navbar-logo" alt="Roxxer" />
          </div>

          <div className="nav-center">
            <Link href="/about">About</Link>
            <Link href="/technology">Shop Parts</Link>
            <Link href="/careers">Careers</Link>
            <Link href="/prebooking">Premium Area</Link>
            <Link href="/roxxer-lab">Roxxer Lab</Link>
          </div>

          <button className="subscribe-btn"><span>Subscribe</span></button>
        </div>

        {children}
      </body>
    </html>
  );
}
